classdef ReferencePsi < OI.Plugins.PluginBase
    properties
        inputs = { ...
            OI.Data.Sentinel1DownloadSummary(), ...
            OI.Data.Catalogue(), ...
            OI.Data.OrbitSummary() , ...
            OI.Data.PreprocessedFiles(), ...
            OI.Data.GeocodingSummary(), ...
            OI.Data.CoregistrationSummary(), ...
            OI.Data.BlockingSummary(), ...
            OI.Data.BlockBaselineSummary(), ...
            OI.Data.BlockPsiSummary() ...
            }
            outputs = {OI.Data.PsiSummary()}
        id = 'ReferencePSI'
    end

    methods
        function this = run( this, engine, ~ )
            for ii = 1:numel(this.inputs)
                data = engine.load(this.inputs{ii});
                if isempty(data)
                    engine.ui.log('debug', 'No data found for %s', this.inputs{ii}.id);
                    return % the engine will queue a job to generate the input
                end
            end
            this.isFinished = true;
            engine.save( this.outputs{1} );
        end
    end

end